// GENERATED by `cargo test -p artaveo-shared` from shared/src/lib.rs — do not edit.

export type RpcRequest = { method: string, params: unknown, 
/**
 * Session token from `auth.login`; absent for public methods.
 */
token: string | null, };

export type RpcResponse = { "status": "ok", result: unknown, } | { "status": "error", error: RpcError, };

export type RpcError = { code: ErrorCode, 
/**
 * Developer-facing detail (English, logged); never shown verbatim to users.
 */
detail: string, 
/**
 * The request parameter at fault (e.g. `username`, `owner_password`), so
 * the UI shows the message under that exact input (OF-002). `None` for
 * errors that are not about one field.
 */
field: string | null, 
/**
 * Which rule failed; the UI translates it (`error.rule.<rule>`).
 */
rule: ValidationRule | null, };

export type ValidationRule = "required" | "username_format" | "username_taken" | "password_too_short" | "wrong_password" | "display_name_length" | "clinic_name_length" | "role_not_assignable" | "owner_immutable" | "color_format" | "time_format" | "working_hours" | "session_timeout_range" | "backup_hour_range" | "backup_keep_range" | "logo_type" | "logo_size" | "recovery_key" | "invalid_params" | "full_name_length" | "phone_format" | "patient_not_found" | "date_format" | "age_range" | "cannot_merge_self" | "attachment_type" | "attachment_size" | "import_file_type" | "tooth_format" | "possible_duplicate" | "doctor_not_found" | "doctor_inactive" | "chair_not_found" | "chair_inactive" | "chair_not_allowed" | "chair_name_length" | "chair_name_taken" | "specialty_length" | "user_already_doctor" | "user_not_found" | "appointment_not_found" | "recall_not_found" | "patient_merged" | "time_range" | "duration_range" | "doctor_busy" | "chair_busy" | "patient_busy" | "outside_working_hours" | "doctor_on_break" | "doctor_on_leave" | "schedule_overlap" | "leave_range" | "invalid_transition" | "not_editable" | "repeat_months_range" | "role_label_length" | "role_label_taken" | "role_not_found" | "role_system" | "role_in_use" | "permission_unknown" | "permission_not_allowed" | "permissions_empty" | "self_lockout" | "not_today" | "patient_has_open_appointments" | "import_file_read" | "import_no_name_column" | "import_column";

export type ErrorCode = "not_set_up" | "already_set_up" | "unauthenticated" | "session_expired" | "session_locked" | "forbidden" | "invalid_credentials" | "account_locked" | "recovery_key_invalid" | "validation" | "conflict" | "not_found" | "unknown_method" | "internal";

export type Empty = Record<symbol, never>;

export type AppState = "needs_setup" | "ready";

export type Language = "fa" | "ps" | "en";

export type AppStatus = { state: AppState, version: string, environment: string, clinic_name: string | null, default_language: Language, };

export type CalendarSystem = "shamsi" | "gregorian";

export type ClinicMode = "solo" | "multi";

export type InstallMode = "single" | "server" | "client";

export type ThemePreference = "light" | "dark" | "system";

export type DayHours = { day: number, closed: boolean, 
/**
 * "HH:MM", 24-hour.
 */
open: string | null, close: string | null, };

export type ClinicProfile = { name: string, default_language: Language, logo_path: string | null, province_id: string | null, district_id: string | null, address: string | null, phone: string | null, calendar_system: CalendarSystem, clinic_mode: ClinicMode, install_mode: InstallMode, theme: ThemePreference, color_primary: string, color_secondary: string, color_accent: string, working_hours: Array<DayHours>, 
/**
 * Set once, the first time the wizard's Trial step is acknowledged.
 * No license enforcement yet — the real system is Phase 10.
 */
trial_started_at: string | null, };

export type SetupParams = { clinic_name: string, owner_username: string, owner_display_name: string, owner_password: string, language: Language, install_mode: InstallMode, province_id: string | null, district_id: string | null, address: string | null, phone: string | null, 
/**
 * Base64-encoded logo image (png/jpg/webp), optional.
 */
logo_base64: string | null, logo_file_name: string | null, calendar_system: CalendarSystem, clinic_mode: ClinicMode, theme: ThemePreference, color_primary: string, color_secondary: string, color_accent: string, working_hours: Array<DayHours>, trial_acknowledged: boolean, };

export type ClinicLogo = { data_url: string | null, };

export type SetLogoParams = { logo_base64: string | null, logo_file_name: string | null, };

export type SetupResult = { 
/**
 * Shown once; the Owner must print or write it down (ADR-04).
 */
recovery_key: string, };

export type LoginParams = { username: string, password: string, };

export type UserInfo = { id: string, username: string, display_name: string, role: string, 
/**
 * Name of a clinic-made role; built-in roles have none (the UI translates `role`).
 */
role_label: string | null, is_active: boolean, version: number, };

export type SessionInfo = { token: string, user: UserInfo, permissions: Array<string>, timeout_minutes: number, locked: boolean, };

export type SessionState = { locked: boolean, 
/**
 * Seconds of inactivity left before the screen locks.
 */
idle_seconds_left: number, };

export type UnlockParams = { password: string, };

export type TouchParams = { 
/**
 * How long ago the user last moved the mouse, scrolled or typed, so the
 * idle timer is exact although heartbeats are sent only every few seconds.
 */
idle_ms: number, };

export type ChangePasswordParams = { current_password: string, new_password: string, };

export type RecoverOwnerParams = { recovery_key: string, new_password: string, };

export type CreateUserParams = { username: string, display_name: string, password: string, role: string, };

export type UpdateUserParams = { id: string, 
/**
 * The `version` the client last saw (optimistic locking, Data Conventions 1.4).
 */
version: number, display_name: string, role: string, is_active: boolean, };

export type RoleInfo = { code: string, 
/**
 * The name a clinic gave a custom role; system roles have none (the UI translates their code).
 */
label: string | null, is_system: boolean, permissions: Array<string>, 
/**
 * Active users currently holding the role.
 */
user_count: number, version: number, };

export type PermissionInfo = { code: string, 
/**
 * False for permissions only the built-in roles carry (e.g. `backup.restore`, Owner-only).
 */
assignable: boolean, };

export type CreateRoleParams = { label: string, permissions: Array<string>, };

export type UpdateRoleParams = { code: string, version: number, label: string, permissions: Array<string>, };

export type DeleteRoleParams = { code: string, version: number, };

export type ResetPasswordParams = { id: string, new_password: string, };

export type UserIdParams = { id: string, };

export type ReferenceListParams = { type_code: string, language: Language, };

export type DistrictListParams = { province_id: string, language: Language, };

export type LanguageParams = { language: Language, };

export type LabeledItem = { id: string, code: string, label: string, };

export type BackupInfo = { id: string, file_name: string, created_at: string, size_bytes: number, 
/**
 * "manual" | "daily" | "pre_migration"
 */
kind: string, verified: boolean, };

export type AuditListParams = { limit: number, offset: number, 
/**
 * Narrows to one record's history (e.g. a patient's Audit History tab, 3.6).
 */
entity_id: string | null, };

export type AuditEntry = { id: number, at: string, user_id: string | null, username: string | null, action: string, entity: string | null, entity_id: string | null, old_value: string | null, new_value: string | null, computer: string, };

export type Settings = { session_timeout_minutes: number, daily_backup_hour: number, backup_keep_daily: number, };

export type DatabaseInfo = { encrypted: boolean, cipher_version: string, sqlite_version: string, 
/**
 * "windows_dpapi_machine" | "insecure_dev_file"
 */
key_protection: string, schema_version: number, size_bytes: number, };

export type IntegrityInfo = { 
/**
 * "pending" | "running" | "ok" | "failed"
 */
status: string, checked_at: string | null, detail: string | null, };

export type SystemInfo = { app_version: string, git_commit: string, 
/**
 * CPU architecture this build was compiled for: "x64" | "x86" | "arm64".
 */
build_arch: string, 
/**
 * The machine's native architecture (differs when emulated, e.g. x86 on ARM64).
 */
machine_arch: string, emulated: boolean, os: string, environment: string, computer_name: string, data_dir: string, log_dir: string, database: DatabaseInfo | null, integrity: IntegrityInfo, last_backup: BackupInfo | null, };

export type PatientStatus = "active" | "inactive";

export type PatientInfo = { id: string, patient_number: string, full_name: string, father_name: string | null, preferred_language: Language | null, gender_id: string | null, date_of_birth: string | null, approximate_age: number | null, phone: string | null, secondary_phone: string | null, province_id: string | null, district_id: string | null, address: string | null, emergency_contact_name: string | null, emergency_contact_phone: string | null, emergency_contact_relationship_id: string | null, referral_source_id: string | null, notes: string | null, registration_date: string, status: PatientStatus, merged_into_id: string | null, version: number, };

export type CreatePatientParams = { full_name: string, father_name: string | null, preferred_language: Language | null, gender_id: string | null, date_of_birth: string | null, approximate_age: number | null, phone: string | null, secondary_phone: string | null, province_id: string | null, district_id: string | null, address: string | null, emergency_contact_name: string | null, emergency_contact_phone: string | null, emergency_contact_relationship_id: string | null, referral_source_id: string | null, notes: string | null, registration_date: string | null, allow_duplicate: boolean, };

export type UpdatePatientParams = { id: string, version: number, full_name: string, father_name: string | null, preferred_language: Language | null, gender_id: string | null, date_of_birth: string | null, approximate_age: number | null, phone: string | null, secondary_phone: string | null, province_id: string | null, district_id: string | null, address: string | null, emergency_contact_name: string | null, emergency_contact_phone: string | null, emergency_contact_relationship_id: string | null, referral_source_id: string | null, notes: string | null, status: PatientStatus, };

export type DuplicateCheckParams = { full_name: string, phone: string | null, };

export type PatientListParams = { query: string | null, status: PatientStatus | null, limit: number, offset: number, };

export type PatientListResult = { items: Array<PatientInfo>, total: number, };

export type PatientIdParams = { patient_id: string, };

export type MergePatientsParams = { keep_id: string, merge_id: string, merge_id_version: number, };

export type MedicalHistoryInfo = { patient_id: string, allergies: string | null, current_medications: string | null, chronic_conditions: string | null, dental_history: string | null, previous_surgeries: string | null, notes: string | null, version: number, };

export type UpdateMedicalHistoryParams = { patient_id: string, version: number, allergies: string | null, current_medications: string | null, chronic_conditions: string | null, dental_history: string | null, previous_surgeries: string | null, notes: string | null, };

export type AttachmentKind = "xray" | "photo" | "document" | "scan" | "consent_form" | "other";

export type AttachmentInfo = { id: string, patient_id: string, kind: AttachmentKind, file_name: string, mime_type: string, size_bytes: number, tooth: string | null, description: string | null, has_thumbnail: boolean, captured_at: string, created_at: string, version: number, };

export type UploadAttachmentParams = { patient_id: string, kind: AttachmentKind, file_name: string, data_base64: string, tooth: string | null, description: string | null, captured_at: string | null, };

export type IdVersionParams = { id: string, version: number, };

export type AttachmentData = { data_url: string, };

export type AttachmentFileParams = { id: string, thumbnail: boolean, };

export type IdParams = { id: string, };

export type ImportError = { row_number: number, 
/**
 * Developer-facing detail (English).
 */
message: string, 
/**
 * The patient field at fault and the rule it broke; the UI translates `rule.<rule>`.
 */
field: ImportField | null, rule: ValidationRule | null, };

export type ImportPreviewRow = { row_number: number, full_name: string, father_name: string | null, phone: string | null, errors: Array<ImportError>, };

export type ImportPatientsParams = { 
/**
 * CSV (UTF-8) or Excel (.xlsx) file, base64.
 */
file_base64: string, file_name: string | null, sheet: string | null, 
/**
 * File column → patient field. Absent = use the automatic guess.
 */
mapping: Array<ColumnMapping> | null, commit: boolean, };

export type ImportPatientsResult = { total: number, imported: number, skipped: number, preview: Array<ImportPreviewRow>, errors: Array<ImportError>, };

export type ExportResult = { csv_base64: string, file_name: string, };

export type ImportField = "full_name" | "father_name" | "phone" | "secondary_phone" | "date_of_birth" | "approximate_age" | "gender" | "province" | "address" | "emergency_contact_name" | "emergency_contact_phone" | "notes" | "registration_date";

export type ColumnMapping = { column: number, field: ImportField, };

export type ImportInspectParams = { file_base64: string, file_name: string, 
/**
 * Sheet of an Excel file; the first sheet when absent.
 */
sheet: string | null, };

export type ImportInspectResult = { 
/**
 * "csv" or "xlsx".
 */
file_kind: string, sheets: Array<string>, sheet: string | null, headers: Array<string>, 
/**
 * The first rows below the header, for the mapping screen.
 */
sample_rows: Array<Array<string>>, total_rows: number, 
/**
 * Automatic guess from the header names (Dari, Pashto and English).
 */
suggested: Array<ColumnMapping>, };

export type AttachmentThumbnail = { id: string, 
/**
 * `data:image/jpeg;base64,…`, or `None` when the file is not an image the Core can shrink.
 */
data_url: string | null, };

export type ActiveStatus = "active" | "inactive";

export type ScheduleSlot = { day: number, start: string, end: string, };

export type LeaveInfo = { id: string, doctor_id: string, 
/**
 * Clinic-local ISO dates, both ends inclusive.
 */
start_date: string, end_date: string, reason: string | null, version: number, };

export type DoctorInfo = { id: string, 
/**
 * The login this doctor signs in with, if any.
 */
user_id: string | null, username: string | null, full_name: string, specialty: string | null, 
/**
 * Calendar colour, `#rrggbb`.
 */
color: string, status: ActiveStatus, sort_order: number, 
/**
 * Weekly working hours. No intervals at all = no hour restriction.
 */
hours: Array<ScheduleSlot>, breaks: Array<ScheduleSlot>, 
/**
 * Chairs this doctor may use; empty = any chair.
 */
chair_ids: Array<string>, leaves: Array<LeaveInfo>, version: number, };

export type DoctorListParams = { include_inactive: boolean, };

export type CreateDoctorParams = { full_name: string, specialty: string | null, color: string, user_id: string | null, };

export type UpdateDoctorParams = { id: string, version: number, full_name: string, specialty: string | null, color: string, status: ActiveStatus, user_id: string | null, };

export type SetScheduleParams = { doctor_id: string, version: number, hours: Array<ScheduleSlot>, breaks: Array<ScheduleSlot>, chair_ids: Array<string>, };

export type AddLeaveParams = { doctor_id: string, start_date: string, end_date: string, reason: string | null, };

export type LeaveResult = { leave: LeaveInfo, 
/**
 * Live appointments of this doctor that fall inside the leave and need rescheduling.
 */
affected_appointments: number, };

export type ChairInfo = { id: string, name: string, status: ActiveStatus, sort_order: number, version: number, };

export type ChairListParams = { include_inactive: boolean, };

export type CreateChairParams = { name: string, };

export type UpdateChairParams = { id: string, version: number, name: string, status: ActiveStatus, };

export type AppointmentStatus = "scheduled" | "confirmed" | "checked_in" | "in_treatment" | "completed" | "cancelled" | "no_show" | "rescheduled";

export type AppointmentInfo = { id: string, patient_id: string, patient_number: string, patient_name: string, patient_phone: string | null, doctor_id: string, doctor_name: string, doctor_color: string, chair_id: string | null, chair_name: string | null, 
/**
 * Clinic-local date (ISO) and 24-hour "HH:MM" start/end; the UI formats them 12-hour.
 */
date: string, start_time: string, end_time: string, 
/**
 * The same instants in UTC (ADR-07).
 */
start_at: string, end_at: string, reason: string | null, notes: string | null, status: AppointmentStatus, is_walk_in: boolean, 
/**
 * Ticket of the day, assigned at check-in.
 */
queue_number: number | null, checked_in_at: string | null, treatment_started_at: string | null, completed_at: string | null, cancelled_at: string | null, cancel_reason: string | null, rescheduled_from_id: string | null, rescheduled_to_id: string | null, version: number, };

export type CreateAppointmentParams = { patient_id: string, doctor_id: string, chair_id: string | null, date: string, start_time: string, end_time: string, reason: string | null, notes: string | null, 
/**
 * Book outside the doctor's hours / during a break / on a leave day anyway.
 */
override_schedule: boolean, 
/**
 * Booking made from the recall list (4.6): the recall becomes `booked`.
 */
recall_id: string | null, };

export type UpdateAppointmentParams = { id: string, version: number, doctor_id: string, chair_id: string | null, date: string, start_time: string, end_time: string, reason: string | null, notes: string | null, override_schedule: boolean, };

export type RescheduleAppointmentParams = { id: string, version: number, doctor_id: string, chair_id: string | null, date: string, start_time: string, end_time: string, override_schedule: boolean, };

export type AppointmentListParams = { 
/**
 * Clinic-local ISO dates, both ends inclusive. Required unless `patient_id` is given.
 */
date_from: string | null, date_to: string | null, doctor_id: string | null, chair_id: string | null, patient_id: string | null, 
/**
 * Empty = every status.
 */
statuses: Array<AppointmentStatus>, limit: number, offset: number, };

export type AppointmentCountsParams = { date_from: string, date_to: string, doctor_id: string | null, };

export type DayCount = { date: string, 
/**
 * Every appointment of the day except cancelled / rescheduled ones.
 */
total: number, 
/**
 * Not yet finished (scheduled, confirmed, checked-in, in treatment).
 */
open: number, };

export type SetAppointmentStatusParams = { id: string, version: number, status: AppointmentStatus, 
/**
 * Why it was cancelled (optional).
 */
reason: string | null, 
/**
 * With `completed`: schedule the patient's next visit / recall in the same step (4.6).
 */
follow_up: FollowUpInput | null, };

export type WalkInParams = { patient_id: string, doctor_id: string, chair_id: string | null, reason: string | null, 
/**
 * Expected length; default 30 minutes.
 */
duration_minutes: number | null, };

export type RecallKind = "checkup" | "cleaning" | "follow_up" | "no_show" | "other";

export type RecallStatus = "pending" | "contacted" | "booked" | "done" | "dismissed";

export type FollowUpInput = { due_date: string, kind: RecallKind, 
/**
 * Recurring recall: once its visit is completed, the next one is created this many months later.
 */
repeat_months: number | null, note: string | null, };

export type RecallInfo = { id: string, patient_id: string, patient_number: string, patient_name: string, patient_phone: string | null, kind: RecallKind, due_date: string, repeat_months: number | null, note: string | null, status: RecallStatus, appointment_id: string | null, source_appointment_id: string | null, last_contacted_at: string | null, contact_note: string | null, version: number, };

export type CreateRecallParams = { patient_id: string, kind: RecallKind, due_date: string, repeat_months: number | null, note: string | null, };

export type UpdateRecallParams = { id: string, version: number, kind: RecallKind, due_date: string, repeat_months: number | null, note: string | null, };

export type SetRecallStatusParams = { id: string, version: number, status: RecallStatus, note: string | null, };

export type RecallListParams = { patient_id: string | null, 
/**
 * Empty = the call list (pending + contacted).
 */
statuses: Array<RecallStatus>, 
/**
 * Clinic-local ISO dates; `due_until` lets the call list show "due within two weeks".
 */
due_from: string | null, due_until: string | null, limit: number, offset: number, };

export type RecallListResult = { items: Array<RecallInfo>, total: number, };

export interface Api {
  "app.status": { params: Empty; result: AppStatus };
  "app.setup": { params: SetupParams; result: SetupResult };
  "app.clinic_logo": { params: Empty; result: ClinicLogo };
  "auth.login": { params: LoginParams; result: SessionInfo };
  "auth.recover_owner": { params: RecoverOwnerParams; result: Empty };
  "auth.logout": { params: Empty; result: Empty };
  "auth.change_password": { params: ChangePasswordParams; result: Empty };
  "session.state": { params: Empty; result: SessionState };
  "session.touch": { params: TouchParams; result: SessionState };
  "session.lock": { params: Empty; result: SessionState };
  "session.unlock": { params: UnlockParams; result: SessionState };
  "users.list": { params: Empty; result: Array<UserInfo> };
  "users.create": { params: CreateUserParams; result: UserInfo };
  "users.update": { params: UpdateUserParams; result: UserInfo };
  "users.reset_password": { params: ResetPasswordParams; result: UserInfo };
  "users.unlock": { params: UserIdParams; result: UserInfo };
  "roles.list": { params: Empty; result: Array<RoleInfo> };
  "roles.create": { params: CreateRoleParams; result: RoleInfo };
  "roles.update": { params: UpdateRoleParams; result: RoleInfo };
  "roles.delete": { params: DeleteRoleParams; result: Empty };
  "permissions.list": { params: Empty; result: Array<PermissionInfo> };
  "reference.list": { params: ReferenceListParams; result: Array<LabeledItem> };
  "geo.provinces": { params: LanguageParams; result: Array<LabeledItem> };
  "geo.districts": { params: DistrictListParams; result: Array<LabeledItem> };
  "clinic.get": { params: Empty; result: ClinicProfile };
  "clinic.update": { params: ClinicProfile; result: ClinicProfile };
  "clinic.set_logo": { params: SetLogoParams; result: ClinicLogo };
  "settings.get": { params: Empty; result: Settings };
  "settings.update": { params: Settings; result: Settings };
  "patients.list": { params: PatientListParams; result: PatientListResult };
  "patients.get": { params: PatientIdParams; result: PatientInfo };
  "patients.create": { params: CreatePatientParams; result: PatientInfo };
  "patients.update": { params: UpdatePatientParams; result: PatientInfo };
  "patients.delete": { params: IdVersionParams; result: Empty };
  "patients.check_duplicate": { params: DuplicateCheckParams; result: Array<PatientInfo> };
  "patients.merge": { params: MergePatientsParams; result: PatientInfo };
  "patients.import_inspect": { params: ImportInspectParams; result: ImportInspectResult };
  "patients.import": { params: ImportPatientsParams; result: ImportPatientsResult };
  "patients.export": { params: Empty; result: ExportResult };
  "medical_history.get": { params: PatientIdParams; result: MedicalHistoryInfo };
  "medical_history.update": { params: UpdateMedicalHistoryParams; result: MedicalHistoryInfo };
  "attachments.list": { params: PatientIdParams; result: Array<AttachmentInfo> };
  "attachments.upload": { params: UploadAttachmentParams; result: AttachmentInfo };
  "attachments.delete": { params: IdVersionParams; result: Empty };
  "attachments.file": { params: AttachmentFileParams; result: AttachmentData };
  "attachments.thumbnails": { params: PatientIdParams; result: Array<AttachmentThumbnail> };
  "doctors.list": { params: DoctorListParams; result: Array<DoctorInfo> };
  "doctors.create": { params: CreateDoctorParams; result: DoctorInfo };
  "doctors.update": { params: UpdateDoctorParams; result: DoctorInfo };
  "doctors.set_schedule": { params: SetScheduleParams; result: DoctorInfo };
  "doctors.add_leave": { params: AddLeaveParams; result: LeaveResult };
  "doctors.delete_leave": { params: IdVersionParams; result: Empty };
  "chairs.list": { params: ChairListParams; result: Array<ChairInfo> };
  "chairs.create": { params: CreateChairParams; result: ChairInfo };
  "chairs.update": { params: UpdateChairParams; result: ChairInfo };
  "appointments.list": { params: AppointmentListParams; result: Array<AppointmentInfo> };
  "appointments.counts": { params: AppointmentCountsParams; result: Array<DayCount> };
  "appointments.get": { params: IdParams; result: AppointmentInfo };
  "appointments.create": { params: CreateAppointmentParams; result: AppointmentInfo };
  "appointments.update": { params: UpdateAppointmentParams; result: AppointmentInfo };
  "appointments.reschedule": { params: RescheduleAppointmentParams; result: AppointmentInfo };
  "appointments.set_status": { params: SetAppointmentStatusParams; result: AppointmentInfo };
  "appointments.walk_in": { params: WalkInParams; result: AppointmentInfo };
  "recalls.list": { params: RecallListParams; result: RecallListResult };
  "recalls.create": { params: CreateRecallParams; result: RecallInfo };
  "recalls.update": { params: UpdateRecallParams; result: RecallInfo };
  "recalls.set_status": { params: SetRecallStatusParams; result: RecallInfo };
  "backup.create": { params: Empty; result: BackupInfo };
  "backup.list": { params: Empty; result: Array<BackupInfo> };
  "audit.list": { params: AuditListParams; result: Array<AuditEntry> };
  "system.info": { params: Empty; result: SystemInfo };
}

export const PUBLIC_METHODS = ["app.status","app.setup","app.clinic_logo","auth.login","auth.recover_owner"] as const;
